pipeline {
    agent any
    tools {

    stages {
        stage('Building image') {
          steps{
            script {
              dockerImage = docker.build andrewolegovich/aws-http-server
            }
          }
        }
        stage('Deploy Image') {
          steps{
            script {
              docker.withRegistry( '', dockerhub ) {
                dockerImage.push("$BUILD_NUMBER")
                 dockerImage.push('latest')

              }
            }
          }
        }
    }
}