pipeline {
    agent any

    stages {
        stage("Go test") {
            steps {
                sh 'go test -v ./...'
            }
        }
        stage("Docker build") {
            steps {
                script {
                    def customImage = docker.build('andrewolegovich/aws-http-server', "./")
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                    customImage.push("${env.BUILD_NUMBER}")
                    }
                }
            }
        }
    }
}