apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-server.fullname" . }}
  labels:
    {{- include "http-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "http-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "http-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8070
              protocol: TCP
          env:
            - name: GRPC_ADDR
              value: {{ .Values.grpc_addr}}
            - name: AWS_REGION
              value: {{ .Values.region }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-auth
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-auth
                  key: key