// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AWSServiceClient is the client API for AWSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AWSServiceClient interface {
	StringSend(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type aWSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAWSServiceClient(cc grpc.ClientConnInterface) AWSServiceClient {
	return &aWSServiceClient{cc}
}

func (c *aWSServiceClient) StringSend(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.AWSService/StringSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AWSServiceServer is the server API for AWSService service.
// All implementations must embed UnimplementedAWSServiceServer
// for forward compatibility
type AWSServiceServer interface {
	StringSend(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAWSServiceServer()
}

// UnimplementedAWSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAWSServiceServer struct {
}

func (UnimplementedAWSServiceServer) StringSend(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringSend not implemented")
}
func (UnimplementedAWSServiceServer) mustEmbedUnimplementedAWSServiceServer() {}

// UnsafeAWSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AWSServiceServer will
// result in compilation errors.
type UnsafeAWSServiceServer interface {
	mustEmbedUnimplementedAWSServiceServer()
}

func RegisterAWSServiceServer(s grpc.ServiceRegistrar, srv AWSServiceServer) {
	s.RegisterService(&AWSService_ServiceDesc, srv)
}

func _AWSService_StringSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).StringSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AWSService/StringSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).StringSend(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AWSService_ServiceDesc is the grpc.ServiceDesc for AWSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AWSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AWSService",
	HandlerType: (*AWSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StringSend",
			Handler:    _AWSService_StringSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aws-service.proto",
}
