pipeline {
    agent any

    stages {
        stage('Building image') {
          steps{
            script {
              dockerImage = docker.build andrewolegovich/aws-grpc-server
            }
          }
        }
        stage('Deploy Image') {
          steps{
            script {
              docker.withRegistry( '', dockerhub ) {
                dockerImage.push("$BUILD_NUMBER")
                 dockerImage.push('latest')

              }
            }
          }
        }
    }
}