apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-server.fullname" . }}-svc
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "grpc-server.selectorLabels" . | nindent 4 }}
